---
# This file is used by developers who use ./scripts/deploy.sh to set up a local
# development environment to help with development this module.
version: '3'

services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile-nginx-10

  drupal:
    image: dcycle/drupal:10-fpm-alpine
